import { argon2id, argon2Verify, setWASMModules } from "argon2-wasm-edge";
import argon2WASM from "argon2-wasm-edge/wasm/argon2.wasm";
import blake2bWASM from "argon2-wasm-edge/wasm/blake2b.wasm";

// @ts-ignore `.open-next/worker.js` is generated by `pnpm cf:build`.
import handler from "./.open-next/worker.js";

void setWASMModules({ argon2WASM, blake2bWASM });

Object.assign(globalThis, {
  __CLOUDFLARE_ARGON2_RUNTIME__: {
    argon2id,
    argon2Verify
  }
});

export default {
  fetch: handler.fetch
};
